#!/bin/sh

# lang
uci set luci.main.lang=auto
uci commit luci

# timezone
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai

# ntp server
uci -q delete system.ntp.server
uci add_list system.ntp.server="ntp.aliyun.com"
uci add_list system.ntp.server="time1.cloud.tencent.com"
uci add_list system.ntp.server="time.ustc.edu.cn"
uci add_list system.ntp.server="cn.pool.ntp.org"
uci commit system && service sysntpd reload

# log level
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system

# zram
mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
zram_size=$(echo | awk "{print int($mem_total*0.25/1024)}")
uci set system.@system[0].zram_size_mb="$zram_size"
uci set system.@system[0].zram_comp_algo='lz4'
uci commit system

# nginx
uci set nginx.global.uci_enable='true'
uci del nginx._lan
uci del nginx._redirect2ssl
uci add nginx server
uci rename nginx.@server[0]='_lan'
uci set nginx._lan.server_name='_lan'
uci add_list nginx._lan.listen='80 default_server'
uci add_list nginx._lan.listen='[::]:80 default_server'
#uci add_list nginx._lan.include='restrict_locally'
uci add_list nginx._lan.include='conf.d/*.locations'
uci set nginx._lan.access_log='off; # logd openwrt'
uci commit nginx
service nginx restart



ln -sf /sbin/ip /usr/bin/ip


# luci cache
rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
