#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    config_load mtk_relay
    config_get_bool enabled settings enabled 0
    [ "$enabled" -eq 0 ] && return

    procd_open_instance
    procd_set_param command /bin/sh /usr/bin/mtk_auto_relay.sh
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "mtk_relay"
}
