name: Build Packages

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm_cortex-a5_vfpv4
        branch:
          - openwrt-23.05

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: xd
          PACKAGES: luci-app-adguardhome
          NO_REFRESH_CHECK: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: xd_${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/xd/*.ipk
